### ISSUE TITLE
可以支持真机嘛？

### ISSUE THREAD

**Issue by MasterSumCloud** [xiafeifei/com.tanwan.qiuqiu.yx#1]
我对lua不了解，可以简单解释下整个项目的机制不？交流下，比如这如何获取到数据，球球合成规则，然后怎么操作的 😃  非常感谢

**Comment by xiafeifei** [comment]
支持，但是需要 root！不然不能写入缓存 注入lua 文件。项目机制就是注入请求数据回传 nodejs server 处理，并返回需要作出的响应操作！球球合成规则就是 根据同级、同类、或者通用合成球球进行匹配合并（棋盘满了才会进行合并）。操作教程，有个bilibili链接。

**Comment by MasterSumCloud** [comment]
PS C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5> npm i
npm WARN hello-node-server@1.0.0 No repository field.

audited 96 packages in 2.52s
found 0 vulnerabilities

PS C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5> npm run start                                                     
> hello-node-server@1.0.0 start C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5
> node index.js

internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module './gameData.cfg.dragon.ball'
Require stack:
- C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5\utils\gameData.js
- C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5\utils\cache.js
- C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5\lib\api.js
- C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\Eagle\Desktop\com.tanwan.qiuqiu.yx-1.0.5\utils\gameData.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Eagle\\Desktop\\com.tanwan.qiuqiu.yx-1.0.5\\utils\\gameData.js',
    'C:\\Users\\Eagle\\Desktop\\com.tanwan.qiuqiu.yx-1.0.5\\utils\\cache.js',
    'C:\\Users\\Eagle\\Desktop\\com.tanwan.qiuqiu.yx-1.0.5\\lib\\api.js',
    'C:\\Users\\Eagle\\Desktop\\com.tanwan.qiuqiu.yx-1.0.5\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-node-server@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-node-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eagle\AppData\Roaming\npm-cache\_logs\2020-08-07T12_48_38_956Z-debug.log

**Comment by MasterSumCloud** [comment]
下载你最新的  启动OK，但是近游戏没反应，然后下载1.0.5 启动服务会报错

**Comment by xiafeifei** [comment]
你可以照着视频教程操作！需要拷贝 lua 到游戏目录内，IP也需要配置正确！游戏启动如果有问号小图标才是注入成功！

**Comment by MasterSumCloud** [comment]
我也是一名开发，所以很低级的错误，我不会犯的。下载master 最新  服务器启动OK，IP什么都OK，但是最后没反应。有其他联系方式方便交流下？

**Comment by MasterSumCloud** [comment]
https://qqyx.gzyueyou.cn/
这是我的版本，不知道是不是因为版本问题。我看到我们唯一却别就是渠道版本不一样。你可以先测试一下

**Comment by xiafeifei** [comment]
我测试了，可以！只不过你这个跃游版本渠道路径是 `/data/data/com.gzyy.qqyxdt/file/com.tanwan.qiuqiu.yx/src/` 。

**Comment by MasterSumCloud** [comment]
![QQ截图20200807213245](https://user-images.githubusercontent.com/24472270/89651141-0c693f80-d8f6-11ea-8097-0d79713d48c6.png)

**Comment by MasterSumCloud** [comment]
![QQ截图20200807213245](https://user-images.githubusercontent.com/24472270/89651219-2e62c200-d8f6-11ea-9437-1932997ca318.png)

**Comment by MasterSumCloud** [comment]
![QQ截图20200807213421](https://user-images.githubusercontent.com/24472270/89651265-41759200-d8f6-11ea-8098-e116f3eeb75c.png)

**Comment by MasterSumCloud** [comment]
图能看到不   我觉得我配置OK的

**Comment by xiafeifei** [comment]
![QQ截图20200807215310](https://user-images.githubusercontent.com/19986597/89652692-7387f380-d8f8-11ea-8de9-20fe48bf1378.png)

看不到图片，你邮箱发我吧。 demo2013@vip.qq.com

**Comment by MasterSumCloud** [comment]
经过测试我转战夜神模拟器，是OK的，可能是模拟器支持问题。这个不太清楚
